FROM node:20

WORKDIR /app

# Copia os arquivos de dependência
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o resto do projeto
COPY . .

# Expõe a porta padrão do Vite
EXPOSE 5173

# O comando para iniciar o servidor de desenvolvimento
CMD ["npm", "run", "dev", "--", "--host"]