version: '3.8'
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: financas_front_dev
    ports:
      - "3000:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
