version: "3.8"
services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: financas_front_dev
    ports:
      - "80:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./scripts:/app/scripts
      - /app/node_modules
